site_name: My Docs
site_description: '自分のページ'
site_author: 'nakano16180'

# Copyright
copyright: 'Copyright (c) 2020'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'

# Options
extra:
  palette:
    primary: 'Light Blue'
    accent: 'Orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  social:
  - type: github
    link: https://github.com/nakano16180
  - type: twitter
    link: https://twitter.com/newton112358

# Extensions
markdown_extensions:
  - codehilite:
  - admonition:
  - toc:
      permalink: '#'

# Page tree
nav:
  - Introduction: index.md
  - About Me: 'about.md'
  - 興味のあること: interest.md
  - Python:
    - Masonite: ./Python/masonite.md
  - RL:
    - Pythonで学ぶ強化学習: ./RL/python_RL.md
    - Gym Ignition: ./RL/gym_ignition.md
  - インフラ:
    - Minio: ./dev/minio.md
  - Nodejs:
    - API server: ./Nodejs/API.md