site_name: My Docs
site_description: "自分のページ"
site_author: "nakano16180"
site_url: https://nakano16180.github.io/myHobby/

# Repository
repo_name: nakano16180/myHobby
repo_url: https://github.com/nakano16180/myHobby
edit_uri: ""

# Copyright
copyright: "Copyright (c) 2021"

# Documentation and theme
docs_dir: "docs"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
  palette:
    primary: Light Blue
    accent: Orange
  font:
    text: Roboto
    code: Roboto Mono

# Extensions
markdown_extensions:
  - codehilite:
  - admonition:
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search

# Page tree
nav:
  - Introduction: index.md
  - About Me: 
    - About me: about.md
    - 成果物: ./dev/deliverable.md
  - 学習記録:
      - ドキュメント: ./dev/document.md
      - 開発環境:
          - Linux: ./dev/linux.md
          - Git: ./dev/git.md
          - Docker: ./dev/docker.md
          - Slack: ./dev/slack-extend.md
      - インフラ:
          - AWS:
              - docker-lambda: ./dev/docker-lambda.md
              - Minio: ./dev/minio.md
          - Kubernetes: ./dev/kubernetes.md
      - Python:
          - python: ./Python/python.md
          - DB: ./Python/database.md
          - Flask: ./Python/flask.md
          - Masonite: ./Python/masonite.md
      - Nodejs:
          - nodejs: ./Nodejs/nodejs.md
          - API server: ./Nodejs/API.md
          - React: ./Nodejs/React.md
      - ML:
          - Tools: ./ML/ml-tools.md
      - RL:
          - Gym Ignition: ./RL/gym_ignition.md

